# Generated by Django 5.2 on 2025-04-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Imagens do produto', 'verbose_name_plural': 'Imagens do produto'},
        ),
    ]
